name: Code Quality Check

on:
  push:
    branches: [dev]

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Run Flake8
      run: |        
        pip install flake8  
        flake8 .
