name: Unit Testing

on:
  push:
    branches:
      - dev

jobs:
  unit_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Install flake8
        run: |
          pip install flake8

      # Add additional steps if necessary to set up your test environment

      - name: Run unit tests
        run: |
          # Replace this with your actual command to run unit tests
          python path/to/your/test_script.py

      # Fail the workflow if any step above fails
      - name: Fail the workflow on error
        if: ${{ failure() }}
        run: exit 1
